### ISSUE TITLE
spark 2.3.1

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad-spark#16]
Hello

Is any plans to do this? or this project is dead?

**Comment by schmichael** [comment]
Hi @tantra35! Sorry for the lack of activity recently. We're hoping to dedicate someone to this project very soon!

**Comment by tantra35** [comment]
We just create patch for 2.3.1 perhaps it will be helpful

[spark.patch.gz](https://github.com/hashicorp/nomad-spark/files/2212280/spark.patch.gz)

But we doesn't include changes in `core/src/main/scala/org/apache/spark/scheduler/cluster/CoarseGrainedSchedulerBackend.scala`

**Comment by barnardb** [comment]
https://github.com/hashicorp/nomad-spark/tree/nomad-on-spark-2.3.1
https://github.com/hashicorp/nomad-spark/releases/tag/v2.3.1-nomad-0.7.0-20180722

Apologies for the wait.
