### ISSUE TITLE
Spark 2.3.2 is out

### ISSUE THREAD

**Issue by tantra35** [hashicorp/nomad-spark#18]
Thanks for good patch, but spark 2.3.2 released

**Comment by memelet** [comment]
2.4.0 even

**Comment by tantra35** [comment]
If anybody interested we build our version of spark 2.3.2 on nomad without hadoop(we use external hadoop 2.9.1) 

https://yadi.sk/d/iKe9WH0JJy3aaw

**Comment by cgbaker** [comment]
Releases of 2.4.0, 2.3.2 and 2.2.2 with support for Nomad are available now.
