### ISSUE TITLE
spark 2.4.0 with scala 2.12 support?

### ISSUE THREAD

**Issue by wlk** [hashicorp/nomad-spark#22]
Can you clarify if spark 2.4.0 with scala 2.12 is supported?

I couldn't find any information about compatible releases.

It looks like your examples project: https://s3.amazonaws.com/nomad-spark/spark-examples_2.11-2.4.0.jar is published only for 2.11

**Comment by cgbaker** [comment]
Hi Wojciech,

I didn't not compile 2.4.0 using 2.12, just 2.11. I will publish new
binaries for 2.12 asap. Thanks for pointing this out.

cb

**Comment by alkagin** [comment]
Hi,

Any news on spark 2.4.0 w scala 2.12? The last Spark release (2.4.3) uses scala 2.12 as default.

**Comment by cgbaker** [comment]
Hi, I'm sorry, I've been caught up in core Nomad work. I'll try to do this
ASAP.

**Comment by cgbaker** [comment]
I have updated the [last 2.4.0](https://github.com/hashicorp/nomad-spark/releases/tag/v2.4.0-nomad-0.8.6-20181220) with a 2.12 build. I have also uploaded a 2.12 build of the examples to the S3 bucket:
https://nomad-spark.s3.amazonaws.com/spark-examples_2.12-2.4.0.jar

Apologies for the delay on this. On the next set of releases, I'll try to remember to release 2.12 distributions as well.

**Comment by cgbaker** [comment]
Spark 2.4.3 with Scala 2.12 has been release: https://github.com/hashicorp/nomad-spark/releases/tag/v2.4.3.0
