### ISSUE TITLE
[bug] driver task group must be 'driver' for job monitoring to work correctly

### ISSUE THREAD

**Issue by ryanmickler** [hashicorp/nomad-spark#5]
I was noticing that my scheduling method (the one that calls `spark-submit -monitorUntil=complete` was never successfully detecting the job was complete. I traced this down to me using an old default template for submitting spark-nomad jobs, which has the driver a group name as `driver-group-name`.

I noticed that this is corrected in the template provided here: https://www.nomadproject.io/guides/spark/customizing.html

Perhaps the documentation should be updated to state that the group being named `driver` is a requirement for this to work. My impression from the docs is that only the appropriate task meta is a requirement.

I tracked it down to hard coded `driver` strings here
https://github.com/hashicorp/nomad-spark/blob/a5214bc5874ea4de552951c2c6a42873fc61f3f3/resource-managers/nomad/src/main/scala/org/apache/spark/deploy/nomad/NomadClusterModeLauncher.scala#L94
https://github.com/hashicorp/nomad-spark/blob/a5214bc5874ea4de552951c2c6a42873fc61f3f3/resource-managers/nomad/src/main/scala/org/apache/spark/deploy/nomad/NomadClusterModeLauncher.scala#L103

**Comment by barnardb** [comment]
Thanks for the bug report, @ryanmickler, and for digging into the code to pinpoint the issue.
